force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Client Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Hash__c.field-meta.xml
<CustomField>
    <fullName>Hash__c</fullName>
    <label>Hash</label>
    <length>128</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/RestChangePassword.cls
@RestResource(UrlMapping='/Client__c/change/*')
global with sharing class RestChangePassword {
    @HttpPost
    global static void changeHash() {
        String jsonBody = RestContext.request.requestBody.toString();

        ClientWrapper clientNew = (ClientWrapper) JSON.deserialize(jsonBody, ClientWrapper.class);

        if(!isHashValid(clientNew.hash)) {
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize('Invalid hash'));
        }

        Client__c clientOld = getClient(clientNew.hash);

        if(clientOld != null) {
            changeClientHash(clientOld, clientNew.hash);

            RestContext.response.statusCode = 200;
        } else {
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize('Invalid Client hash'));
        }
    }

    private static Client__c getClient(String hash) {
        List<Client__c> clients = [SELECT Hash__c FROM Client__c];
        for (Client__c client : clients) {
            if (client.Hash__c == hash) {
                return client;
            }
        }
        return null;
    }

    private static void changeClientHash(Client__c client, String hash) {
        client.Hash__c = hash;

        update client;
    }

    private static boolean isHashValid(String hash) {
        return hash.length() == 64;
    }
}