force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Client Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Hash__c.field-meta.xml
<CustomField>
    <fullName>Hash__c</fullName>
    <label>Hash</label>
    <length>128</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Humor</fullName>
            </value>
            <value>
                <fullName>Science fiction</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/tests/RestLoginClient_Test.cls
@isTest
private class RestLoginClientTest {
    
    @isTest
    static void testLoginClient_ValidHash() {
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/Client__c/login/';
        request.httpMethod = 'POST';
        String validHash = 'validHashValue';
        RestLoginClient.ClientWrapper clientWrapper = new RestLoginClient.ClientWrapper();
        clientWrapper.hash = validHash;
        String requestBody = JSON.serialize(clientWrapper);
        request.requestBody = Blob.valueOf(requestBody);
        RestContext.request = request;
        
        Client__c mockClient = new Client__c(Hash__c = validHash);
        insert mockClient;
        
        Item__c mockItem = new Item__c(Genre__c = 'Test Genre', Title__c = 'Test Title');
        insert mockItem;
        Loan__c mockLoan = new Loan__c(Client__c = mockClient.Id, Item__c = mockItem.Id);
        insert mockLoan;
        
        Test.startTest();
        RestLoginClient.loginClient();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
        List<RestLoginClient.LoanWrapper> responseBody = (List<RestLoginClient.LoanWrapper>)JSON.deserialize(RestContext.response.responseBody.toString(), List<RestLoginClient.LoanWrapper>.class);
        System.assertNotEquals(null, responseBody);
        System.assertEquals(1, responseBody.size());
        RestLoginClient.LoanWrapper loan = responseBody[0];
        System.assertEquals(mockLoan.Id, loan.id);
        System.assertEquals(mockLoan.End_Date__c, loan.end_date);
        System.assertEquals(mockItem.Genre__c, loan.genre);
        System.assertEquals(mockItem.Title__c, loan.title);
    }
    
    @isTest
    static void testLoginClient_InvalidHash() {
        RestRequest request = new RestRequest();
        request.requestURI = '/services/apexrest/Client__c/login/';
        request.httpMethod = 'POST';
        String invalidHash = 'invalidHashValue';
        RestLoginClient.ClientWrapper clientWrapper = new RestLoginClient.ClientWrapper();
        clientWrapper.hash = invalidHash;
        String requestBody = JSON.serialize(clientWrapper);
        request.requestBody = Blob.valueOf(requestBody);
        RestContext.request = request;
        
        Test.startTest();
        RestLoginClient.loginClient();
        Test.stopTest();
        
        System.assertEquals(400, RestContext.response.statusCode);
        String expectedResponseBody = JSON.serialize('Invalid Client hash');
        System.assertEquals(expectedResponseBody, RestContext.response.responseBody.toString());
    }
}