force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Borrowed_Items__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_Items__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Borrowed Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Humor</fullName>
            </value>
            <value>
                <fullName>Science fiction</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Publisher</label>
    <referenceTo>Publisher__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Publisher__c/Publisher__c.object-meta.xml
<CustomObject>
    <label>Publisher</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/ItemWrapper.cls
public with sharing class ItemWrapper {
    public String id;
    public List<String> authors;
    public String publisher;
    public String genre;
    public String title;
    public Decimal quantity;
    public Blob cover;
    public Boolean isAvailable;

    public ItemWrapper(Item__c item) {
        this.id = item.Id;
        this.title = item.Name;
        this.authors = null;
        this.publisher = item.Publisher__r.Name;
        this.genre = item.Genre__c;
        this.quantity = item.Quantity__c;
        this.cover = null;
        this.isAvailable = item.Borrowed_Items__c < item.Quantity__c;
    }
    public ItemWrapper(Item__c item,List<String> authors,Blob cover) {
        this.id = item.Id;
        this.title = item.Name;
        this.publisher = item.Publisher__r.Name;
        this.genre = item.Genre__c;
        this.quantity = item.Quantity__c;
        this.cover = cover;
        this.authors = authors;
        this.isAvailable = item.Borrowed_Items__c < item.Quantity__c;
    }
}