force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Crime</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Humor</fullName>
            </value>
            <value>
                <fullName>Science fiction</fullName>
            </value>
            <value>
                <fullName>Thriller</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/wrappers/LoanWrapper.cls
public with sharing class LoanWrapper {
    public LoanWrapper(Loan__c loan) {
        this.loanId = loan.Id;
        this.title = loan.Item__r.Name;
        this.authors = null;
        this.genre = loan.Item__r.Genre__c;
        this.dateDue = loan.End_Date__c;
        this.cover = null;
    }

    public LoanWrapper(Loan__c loan,Blob cover) {
        this.loanId = loan.Id;
        this.title = loan.Item__r.Name;
        this.authors = null;
        this.genre = loan.Item__r.Genre__c;
        this.dateDue = loan.End_Date__c;
        this.cover = cover;
    }

    public LoanWrapper(Loan__c loan,List<String> authors,Blob cover) {
        this.loanId = loan.Id;
        this.title = loan.Item__r.Name;
        this.authors = authors;
        this.genre = loan.Item__r.Genre__c;
        this.dateDue = loan.End_Date__c;
        this.cover = cover;
    }

    public Id loanId;
    public String title;
    public List<String> authors;
    public String genre;
    public Date dateDue;
    public Blob cover;
}