force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Borrowed_Items__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_Items__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Borrowed Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/schedule/ChangeItemsBorrowedNumber.cls
public with sharing class ChangeItemsBorrowedNumber implements Schedulable {
    public void execute(SchedulableContext sc) {
        List<Item__c> itemsToUpdate = new List<Item__c>();
        
        for (Item__c item : [
            SELECT Id, Borrowed_Items__c, (SELECT Id FROM Loans__r WHERE Start_Date__c >= TODAY AND End_Date__c <= TODAY)
            FROM Item__c
        ]) {
            Integer loanCount = item.Loans__r.size();
            
            item.Borrowed_Items__c = loanCount;
            itemsToUpdate.add(item);
        }
        
        if (!itemsToUpdate.isEmpty()) {
            update itemsToUpdate;
        }
    }
}