force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Borrowed_Items__c.field-meta.xml
<CustomField>
    <fullName>Borrowed_Items__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Borrowed Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Loan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/handlers/LoanTriggerHandler.cls
public with sharing class LoanTriggerHandler {
    public static void increaseNumberOfLoansOnItem(List<Loan__c> loans){
        Map<Id,Item__c> items = getItems(loans);
        List<Item__c> itemsToUpdate = new List<Item__c>();
        for(Loan__c loan : loans){
            Item__c item =items.get(loan.Item__c);
            if(item.Borrowed_Items__c < item.Quantity__c){
                item.Borrowed_Items__c ++;
                itemsToUpdate.add(item);
            }else{
                loan.addError('This book has reached its maximum borrowing number');
            }
        }

        update itemsToUpdate;
    }


    private static Map<Id,Item__c> getItems(List<Loan__c> loans){
        List<Id> ids = new List<Id>();

        for(Loan__c loan : loans){
            ids.add(loan.Item__c);
        }

        return new Map<Id,Item__c>([SELECT Id,Quantity__c,Borrowed_Items__c FROM Item__c WHERE Id in : ids]);
    }
}