force-app/main/default/objects/AccountJoinItem__c/AccountJoinItem__c.object-meta.xml
<CustomObject>
    <label>AccountJoinItem</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountJoinItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountJoinItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountJoinItem</relationshipLabel>
    <relationshipName>AccountJoinItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountJoinItem__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>AccountJoinItem</relationshipLabel>
    <relationshipName>AccountJoinItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/utils/ItemUtils.cls
public with sharing class ItemUtils {
    public static Map<Id,List<String>> getAuthorsFromItem(List<Item__c> items){
        Map<Id,List<String>> authors = new Map<Id, List<String>>();

        for(Item__c item : items) {
            if(!authors.containsKey(item.Id)){
                authors.put(item.Id,new List<String>());
            }
            for(AccountJoinItem__c ajItem : item.AccountJoinItem__r) {
                authors.get(item.Id).add(ajItem.Account__r.Name);
            }
        }

        return authors;
    }
}