force-app/main/default/objects/AccountJoinItem__c/AccountJoinItem__c.object-meta.xml
<CustomObject>
    <label>AccountJoinItem</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountJoinItem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountJoinItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountJoinItem</relationshipLabel>
    <relationshipName>AccountJoinItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountJoinItem__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>AccountJoinItem</relationshipLabel>
    <relationshipName>AccountJoinItem</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/aura class/AccountJoinItemController.cls
public without sharing class AccountJoinItemController {
    @AuraEnabled(cacheable=false)
    public static void createAccountJoinItem(Id accountId, Id itemId) {
        AccountJoinItem__c accountJoinItem = new AccountJoinItem__c(Account__c = accountId, Item__c = itemId);
        System.debug('accountJoinItem: ' + accountJoinItem);
        try{
            insert accountJoinItem;
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
        }
    }
}